STATE_PREGAME = 0;
STATE_GAME = 1;
STATE_POSTGAME = 2;

STATE_TIMES = {
	[STATE_PREGAME] = 10,
	[STATE_GAME] = 600,
	[STATE_POSTGAME] = 30
};

SUBSYSTEM_STATE_GOOD = 0;
SUBSYSTEM_STATE_DANGER = 1;
SUBSYSTEM_STATE_BROKEN = 2;