STATE_PREGAME = 0;
STATE_GAME = 1;
STATE_POSTGAME = 2;
STATE_LOST = 3;

STATE_TIMES = {
	[STATE_PREGAME] = 10,
	[STATE_GAME] = 6000,
	[STATE_POSTGAME] = 30
};

SUBSYSTEM_STATE_GOOD = 0;
SUBSYSTEM_STATE_DANGER = 1;
SUBSYSTEM_STATE_BROKEN = 2;

TASK_MASH = 0;
TASK_ALTERNATE = 1;
TASK_ROW = 2;

STAT_TERMINALS = 0;
STAT_DMG = 1;